### ISSUE TITLE
メンバー追加の際に、名前が空でも登録できてしまう

### ISSUE THREAD

**Issue by ryu-ton10** [emusute1212/MakaseteChoiceForAndroid#26]
「メンバー」メニューにおいて、名前が空文字列の場合でもメンバーとして追加されてしまう。
現状は問題ないが、今後機能が増えた時に名前が空のメンバーがあると邪魔になりそう(例えばメンバーのソートとか)なので、
名前でバリデーションを追加した方が良いと思いました(｀･ω･´)

**Comment by emusute1212** [comment]
Fix it!

https://github.com/emusute1212/MakaseteChoiceForAndroid/pull/33
